import express from 'express';
import { bikerController } from '../controller-instances.js';
import { bikerAuthMiddleware } from '../middlewares/auth-middleware.js';

// Router
const router = express.Router();

// Public routes
router.route( '/' )
  .post(
    /*
    #swagger.security = []
    #swagger.summary = 'Create a biker'
    #swagger.description = 'Create a new biker'
    #swagger.requestBody = {
      required: true,
      content: {
        "application/json": {
          schema: {
            oneOf: [
              { $ref: "#/components/schemas/NewLocalBiker" },
              { $ref: "#/components/schemas/NewForeignerBiker" }
            ]
          }
        }
      }
    }
    #swagger.responses[201] = {
      description: 'Bike created successfully',
      content: {
        "application/json": {
          schema: {
            oneOf: [
              { $ref: "#/components/schemas/LocalBiker" },
              { $ref: "#/components/schemas/ForeignerBiker" }
            ]
          }
        }
      }
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/ValidationError" }
          }
        }
      }
    }
    #swagger.responses[409] = {
      description: 'Conflict - Biker cannot be created (e.g., conflicting email)',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/UniqueConstraintError" }
          }
        }
      }
    }
    */
    bikerController.createRecord
  );

router.route( '/:id/confirm' )
  .get(
    /*
    #swagger.security = []
    #swagger.summary = 'Activate biker account'
    #swagger.description = 'Activate a biker's pending account'
    #swagger.parameters['token'] = {
      in: 'query',
      description: 'JWT generated by the server on biker creation',
      required: true,
      schema: { type: 'string' }
    }
    #swagger.responses[204] = {
      description: 'Account activated successfully - No content'
    }
    #swagger.responses[403] = {
      description: 'Forbidden - Invalid request',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/ForbiddenError" }
          }
        }
      }
    }
    #swagger.responses[412] = {
      description: 'Precondition Failed - Account is not pending',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/PreconditionFailedError" }
          }
        }
      }
    }
    */
    bikerController.confirmEmail
  );

router.route( '/login' )
  .post(
    /*
    #swagger.security = []
    #swagger.summary = 'Biker login'
    #swagger.description = 'Biker login'
    #swagger.requestBody = {
      required: true,
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/BikerLogin" }
        }
      }
    }
    #swagger.responses[200] = {
      description: 'Biker logged in successfully',
      content: {
        "application/json": {
          schema: { $ref: '#/components/schemas/JWT' }
        }
      }
    }
    #swagger.responses[401] = {
      description: 'Unauthorized - Incorrect credentials',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/UnauthorizedError" }
          }
        }
      }
    }
    #swagger.responses[404] = {
      description: 'Not Found - Account does not exist',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/NotFoundError" }
          }
        }
      }
    }
    */
    bikerController.login
  );

// Auth middlewares
router.use( [ '/:id' ], bikerAuthMiddleware );

// Protected routes
router.route( '/:id' )
  .put(
    /*
    #swagger.summary = 'Update a biker'
    #swagger.description = 'Update a new biker (Biker access required)'
    #swagger.requestBody = {
      required: true,
      content: {
        "application/json": {
          schema: {
            oneOf: [
              { $ref: "#/components/schemas/UpdateLocalBiker" },
              { $ref: "#/components/schemas/UpdateForeignerBiker" }
            ]
          }
        }
      }
    }
    #swagger.responses[200] = {
      description: 'Bike updated successfully',
      content: {
        "application/json": {
          schema: {
            oneOf: [
              { $ref: "#/components/schemas/UpdatedLocalBiker" },
              { $ref: "#/components/schemas/UpdatedForeignerBiker" }
            ]
          }
        }
      }
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/ValidationError" }
          }
        }
      }
    }
    #swagger.responses[401] = {
      description: 'Unauthorized - Biker authentication required'
    }
    #swagger.responses[403] = {
      description: 'Forbidden - Insufficient credentials'
    }
    #swagger.responses[409] = {
      description: 'Conflict - Biker cannot be updated (e.g., conflicting email)',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/UniqueConstraintError" }
          }
        }
      }
    }
    */
    bikerController.updateRecord
  );

router.route( '/:id/credit-cards' )
  .put(
    /*
    #swagger.summary = "Change credit card"
    #swagger.description = "Change a biker's credit card (Biker access required)"
    #swagger.requestBody = {
      required: true,
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/NewCreditCard" }
        }
      }
    }
    #swagger.responses[204] = {
      description: 'Credit Card changed successfully - No content'
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          examples: {
            error: { $ref: "#/components/examples/ValidationError" }
          }
        }
      }
    }
    #swagger.responses[401] = {
      description: 'Unauthorized - Biker authentication required'
    }
    #swagger.responses[403] = {
      description: 'Forbidden - Insufficient credentials'
    }
    */
    bikerController.changeCreditCard
  );

export default router;
