export default {
  VALIDATION_ERROR: 'VALIDATION_ERROR', 
  UNIQUE_CONSTRAINT_ERROR: 'UNIQUE_CONSTRAINT_ERROR', 
  FOREIGN_KEY_CONSTRAINT_ERROR: 'FOREIGN_KEY_CONSTRAINT_ERROR', 
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR', 
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};
